apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: edu-viktor-tihovskoy
type: Opaque
stringData:
  DEBUG: "true"
  ALLOWED_HOSTS: "localhost,127.0.0.1,edu-viktor-tihovskoy.sirius-k8s.dvmn.org"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "edu-viktor-tihovskoy"
  DB_USER: "edu-viktor-tihovskoy"
  DB_PASSWORD: "SLO1itI@wm6X2LHg"
  DB_HOST: "rc1b-j03a218khoxjlwdi.mdb.yandexcloud.net"
  DB_PORT: "6432"
  SECRET_KEY: "zv^6*k5y@os&2i2&dzh$kj8s3wuwry^)4s8%k)#7apb@15!sdp"
  DATABASE_URL: "postgres://edu-viktor-tihovskoy:SLO1itI@wm6X2LHg@rc1b-j03a218khoxjlwdi.mdb.yandexcloud.net:6432/edu-viktor-tihovskoy"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
  DJANGO_SUPERUSER_PASSWORD: "admin1234"
