apiVersion: batch/v1
kind: Job
metadata:
  name: django-createsuperuser
  namespace: edu-viktor-tihovskoy
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: createsuperuser
          image: tikhovskoi/k8s-test-django:c37b6f0
          envFrom:
            - secretRef:
                name: django-secret
          command:
            - python
          args:
            - manage.py
            - shell
            - -c
            - |
              import os
              from django.contrib.auth import get_user_model
              User = get_user_model()
              if not User.objects.filter(username=os.environ["DJANGO_SUPERUSER_USERNAME"]).exists():
                  User.objects.create_superuser(
                      username=os.environ["DJANGO_SUPERUSER_USERNAME"],
                      email=os.environ["DJANGO_SUPERUSER_EMAIL"],
                      password=os.environ["DJANGO_SUPERUSER_PASSWORD"]
                  )
                  print("Superuser created")
              else:
                  print("Superuser already exists")
