apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: tikhovskoi/k8s-test-django:c37b6f0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: django-secret
          command: ["python"]
          args: ["manage.py", "migrate", "--noinput"]
